### ISSUE TITLE
Verder invullen planner UI

### ISSUE THREAD

**Issue by stgm** [uvapl/spotter#3]
@bjorn-out 
Ik heb twee models gemaakt:

**Schedule** bevat per kalenderweek een datastructuur met daarin de beschikbare slots per uur. Ik ga er vanuit dat de assistenten per uur werken. De datastructuur wordt automatisch geserialiseerd dus `Schedule.first.slots` geeft een hash. Je kunt dan `Schedule.first.slots[1][9]` doen voor de beschikbaarheid op maandag 9 uur - waarbij `Schedule.first` natuurlijk een random week is op dit moment.

**Appointment** bevat afspraken, niet met een datumveld maar met losse velden voor slot/uur/weekdag/maand/jaar. Ik hoop dat dat helpt om efficiënt queries te runnen. `slot` is een integer die aangeeft welk slot binnen het uur de reservering voor is. Ik heb alvast een functie `starting_time` gemaakt die op basis hiervan de exacte startdatum/tijd uitrekent (prinicipe is wellicht ook bruikbaar bij het genereren van opties). Het notes-veld is voor intern gebruik, bv. door de greeter om in de UI iets over de afspraak zichtbaar te houden (bv. dat deze iets later komt ofzo). Ook beschikbaar: status.

Je kunt updaten met `rails db:migrate` en daarna een paar voorbeelden importeren met `rails db:seed`. Die laatste kun je inhoudelijk aanpassen (bijvoorbeeld meer afspraken toevoegen) en evt. meerdere keren draaien.

Zie de seeds file voor wat achtergrond en voorbeeld:
https://github.com/uvapl/spotter/blob/main/db/seeds.rb

Het verzoek is dan of jij kunt kijken of je "opties" kunt genereren voor het maken van de afspraak :-)

Ik zou wellicht zoiets doen:
- 2 opties zo spoedig mogelijk
- 2 opties over een "paar uur"
- 2 opties "morgen"

**Comment by stgm** [comment]
Als je in de problemen komt met de manier waarop de models in elkaar zitten (met name datums/tijden) dan moet je het zeker zeggen! Ik vermoed dat bovenstaande **kan** werken, maar geen idee of het nog fundamenteel fout is :-)

**Comment by bjorn-out** [comment]
Is het niet handiger om hier ook direct rekening te houden met verschillende vakken? Anders moet er in de code voor het genereren van opties mogelijk later weer van alles aangepast worden...

Of is het de bedoeling om per vak een instance te hosten? ;-)

**Comment by stgm** [comment]
Uh ja, zeker! Die ben ik vergeten. Kan ik later vanmiddag even toevoegen.

**Comment by stgm** [comment]
Aangepast in 06c6e213b2dc6bf7455050bf50f1779c2e6e64aa.
Ik heb alvast een tweede route aangemaakt binnen de `PlannerController`, namelijk `show`.
